//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class UnityMetaUtility
{
    public UnityMetaUtility()
    {
    }
}

public class MetaNode : MetaProperty
{
    public List<MetaProperty> propertys = new List<MetaProperty>();

    public override string ToString()
    {
        string str = name + " : \n";
        for (int i = 0; i < propertys.Count; i ++)
        {
        }
        return str;
    }
}

public class MetaProperty
{
    public int deep;
    public string name;
    public string value;

    public virtual string ToString()
    {
        return name + " : " + value; 
    }
}

